-- Bạn hãy copy và dán toàn bộ mã này vào mục [SQL Editor] trên bảng điều khiển Supabase của bạn và nhấn Run (Chạy).

CREATE TABLE IF NOT EXISTS simulation_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bit_length INT NOT NULL,
  eve_present BOOLEAN NOT NULL,
  qber FLOAT NOT NULL,
  is_safe BOOLEAN NOT NULL,
  aes_key VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bật RLS (Row Level Security) cho bảng
ALTER TABLE simulation_sessions ENABLE ROW LEVEL SECURITY;

-- Xóa các policy cũ nếu chúng đã tồn tại để tránh lỗi 42710
DROP POLICY IF EXISTS "Allow anonymous select" ON simulation_sessions;
DROP POLICY IF EXISTS "Allow anonymous insert" ON simulation_sessions;
DROP POLICY IF EXISTS "Allow anonymous delete" ON simulation_sessions;

-- Tạo chính sách (Policy) cấp quyền thao tác cho người dùng ẩn danh (Anon) - chỉ nên dùng cho Demo
CREATE POLICY "Allow anonymous select" ON simulation_sessions FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert" ON simulation_sessions FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anonymous delete" ON simulation_sessions FOR DELETE TO anon USING (true);
